name: Deploy to GH Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: |
        yarn
        (cd example && yarn)
    - name: Build & Deploy
      run: |
        git config --global user.email "aguretsvlad@gmail.com"
        git config --global user.name "vladagurets"
        git remote set-url origin https://${{ secrets.MY_DEPLOY_KEY }}@github.com/vladagurets/react-cancelable.git
        cd example
        yarn build
        yarn deploy
