name: Publish build to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          yarn
          (cd example && yarn)
          yarn pub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
